6sp develop
ClevertecFrontendLab/AnnaBR01 pull request #4
Opened 2023-03-18 22:54 UTC by AnnaBR01

2023-03-18 23:01 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 68%.
Общее количество тестов: 25.
Количество непройденных тестов: 8.

2023-03-19 00:39 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 76%.
Общее количество тестов: 25.
Количество непройденных тестов: 6.

2023-03-19 16:41 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 25.
Количество непройденных тестов: 0.
***
**1-all-buttons.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnnaBR01/1679244086/1-all-buttons.png)
***
**10-selected-day.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnnaBR01/1679244086/10-selected-day.png)
***
**11-booking-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnnaBR01/1679244086/11-booking-error.png)
***
**12-booking-success.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnnaBR01/1679244086/12-booking-success.png)
***
**13-booking-edit-modal-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnnaBR01/1679244086/13-booking-edit-modal-view.png)
***
**14-modal-edited-date.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnnaBR01/1679244086/14-modal-edited-date.png)
***
**15-rate-modal.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnnaBR01/1679244086/15-rate-modal.png)
***
**16-rate-modal-mobile.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnnaBR01/1679244086/16-rate-modal-mobile.png)
***
**17-rate-filled.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnnaBR01/1679244086/17-rate-filled.png)
***
**18-comments-updated-sort.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnnaBR01/1679244086/18-comments-updated-sort.png)
***
**2-booking-modal-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnnaBR01/1679244086/2-booking-modal-view.png)
***
**3-mobile-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnnaBR01/1679244086/3-mobile-view.png)
***
**4-january.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnnaBR01/1679244086/4-january.png)
***
**5-december-2022.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnnaBR01/1679244086/5-december-2022.png)
***
**6-february.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnnaBR01/1679244086/6-february.png)
***
**7-today-is-friday.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnnaBR01/1679244086/7-today-is-friday.png)
***
**8-today-is-saturday.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnnaBR01/1679244086/8-today-is-saturday.png)
***
**9-today-is-sunday.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnnaBR01/1679244086/9-today-is-sunday.png)
***
**edit-mobile-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnnaBR01/1679244086/edit-mobile-view.png)

2023-03-19 19:00 UTC, Ivan6813 requested changes

2023-03-19 19:00 UTC, Ivan6813 commented on src/pages/book/book-page.tsx
> +  useEffect(() => {
как-то не очень выглядят эти 4 useEffect  с почти одинаковым кодом, может стоит сделать один универсальные компонент для отображения ошибок или уведомлений, подумай, если ли такая возможность

2023-03-19 21:04 UTC, AnnaBR01 commented on src/components/book-details/book-details.tsx
> +              <PrimaryButton
Я еще на первом спринте придумала логику следующую: во всем макете, по большей мере, есть три типа кнопок: оранжевая, белая с бордером и серая. Они отличаются, правда, паддингами и визуалом на разных устройствах (что я учитываю пропсами), поэтому они уже переиспользуемые. В идеальном мире, да))) Можно сделать одну кнопку на все приложение (и я запишу это в рефактор кода себе), но, боюсь, это займет сильно больше времени сейчас, чем у меня есть... Учитывая что эти три кнопки уже переиспользуемые по всему приложению, можно оставить рефактор в одну на будущее?

2023-03-19 21:07 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 25.
Количество непройденных тестов: 0.
***
**1-all-buttons.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnnaBR01/1679260022/1-all-buttons.png)
***
**10-selected-day.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnnaBR01/1679260022/10-selected-day.png)
***
**11-booking-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnnaBR01/1679260022/11-booking-error.png)
***
**12-booking-success.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnnaBR01/1679260022/12-booking-success.png)
***
**13-booking-edit-modal-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnnaBR01/1679260022/13-booking-edit-modal-view.png)
***
**14-modal-edited-date.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnnaBR01/1679260022/14-modal-edited-date.png)
***
**15-rate-modal.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnnaBR01/1679260022/15-rate-modal.png)
***
**16-rate-modal-mobile.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnnaBR01/1679260022/16-rate-modal-mobile.png)
***
**17-rate-filled.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnnaBR01/1679260022/17-rate-filled.png)
***
**18-comments-updated-sort.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnnaBR01/1679260022/18-comments-updated-sort.png)
***
**2-booking-modal-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnnaBR01/1679260022/2-booking-modal-view.png)
***
**3-mobile-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnnaBR01/1679260022/3-mobile-view.png)
***
**4-january.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnnaBR01/1679260022/4-january.png)
***
**5-december-2022.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnnaBR01/1679260022/5-december-2022.png)
***
**6-february.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnnaBR01/1679260022/6-february.png)
***
**7-today-is-friday.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnnaBR01/1679260022/7-today-is-friday.png)
***
**8-today-is-saturday.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnnaBR01/1679260022/8-today-is-saturday.png)
***
**9-today-is-sunday.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnnaBR01/1679260022/9-today-is-sunday.png)
***
**edit-mobile-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AnnaBR01/1679260022/edit-mobile-view.png)

2023-03-20 06:08 UTC, Ivan6813 commented on src/components/book-details/book-details.tsx
> +              <PrimaryButton
Хорошо) если кнопки отличаются по виду, то ты можешь сделать параметр view: primary | ghost | secondary ,например, и в зависимости какая кнопка нужна ты передаешь параметр view с нужным значением, например, view="primary" и в зависимости от того какое значение имеет параметр view ты навешиваешь соответственный класс с нужными стилями

2023-03-20 06:08 UTC, Ivan6813 approved these changes

2023-03-20 06:19 UTC, merged